### PR TITLE
Added new initial ui

### PR DESCRIPTION
**Pull request by dtorczynski**
Hey made some updates mostly front end stuff for now, and added some hooks for the back end. Now the front-end is pulling the pictures from the server.  I figured we'd store the pics on server itself since that way we'd have control over them.
I wasn't sure how you were serving up the website.  I used an angular seed project and pulled in our existing files into it, thats where all the thousands of files are coming from. To run it I just did an "npm start" in the swipeStats directory  in a terminal and then went to "localhost:8000" in a browser then the app directory. I forgot how to make it go directly to the index.html, I thought I'd figure it out/remember later.
Next thing I was going to do was add in swipe ability using the swipe.js file and some jquery to make the swiping look cooler than just using a couple buttons. Also add in the back end for the jquery calls already listed in app.js.

### CODE REVIEW

**Comment by gylu** [comment]
nice! Hey can you link the tutorial that you followed, so I can get a better idea of how everything's structured? I followed this for a bit: http://www.bradoncode.com/tutorials/learn-mean-stack-tutorial/, and it's interesting cuz their "app" folder is all backend.

**Comment by dtorczynski** [comment]
Its a 400 mb video, I'm going to try to compress it and upload it to my branch and send a pull request.  Unless you have a better way to get it.

**Comment by dtorczynski** [comment]
Also on the tutorial they don't keep their node_modules (where the 1000s of files are ) on the github repo.  they do a "echo 'node_modules' >> .gitignore" and use a function called "npm shrinkwrap" which saves the versions of the dependencies at the current time, so when the next person wants to run it, they clone the repo, and do an "npm install" which pulls in all the node module dependencies at that point. that's what I'm doing from now on with my new dependencies, not sure how to/what'll happen if we try to remove the existing node modules from the repository.

**Comment by dtorczynski** [comment]
Compressor website is taking forever and crashing.  I got the video from the code school soup to bits for express if you can find it online, you need a subscription for the website but might be on bit torrent or some random place.  otherwise just let me know if you have a large file sharing website you use and I'll send it.

**Comment by gylu** [comment]
ok, don't worry about the video, hehe. I'll check out your slides.
thanks!

**Pull request merged**
